### ISSUE TITLE
False Flags (Spider/FastStairs)

### ISSUE THREAD

**Issue by tombola46** [Elikill58/Negativity#105] opened 2020-04-07 14:55 UTC
**Describe the bug**
1.Spider false flag - when you are climbing up a ladder
2.Faststairs false flag - when pressing space on stairs

**Your plugin version**
1.6

**Your platform version (and precise the platforme (spigot/sponge))**
Spigot 1.8.8

**Screenshots**
none

**Error / Logs**
https://paste.ubuntu.com/p/kbmwMyGtyB/

**Additional context**
none

**Comment by Elikill58** [comment] 2020-04-07 15:05
1. Thanks for report
2. Duplicate of #102

**Closed** 2020-04-07 16:11 UTC
Labels: false positive
