### ISSUE TITLE
nofall false positive when falling next to glass pane

### ISSUE THREAD

**Issue by spetznack** [Elikill58/Negativity#188] opened 2020-10-13 17:45 UTC
**Describe the bug**
nofall false positive when falling next to glass pane

**Your plugin version**
1.9.5

**Your platform version (and precise the platforme (spigot/sponge))**
paperspigot 1.16.3

**Screenshots**
![negativity nofall false positive when falling next to glass pane](https://user-images.githubusercontent.com/1935616/95889835-42f28900-0d83-11eb-8555-188bfe842036.gif)

Also happens with trapdoors: 
![image](https://user-images.githubusercontent.com/1935616/95891766-d3ca6400-0d85-11eb-8342-e2e661c22bfa.png)

Fences:
![image](https://user-images.githubusercontent.com/1935616/95891841-eba1e800-0d85-11eb-9152-3f7d3f8655dd.png)

vertical and horizontal chains:
![image](https://user-images.githubusercontent.com/1935616/95892090-420f2680-0d86-11eb-8381-06eafdb13cb6.png)

open and closed fencegates:
![image](https://user-images.githubusercontent.com/1935616/95892167-64a13f80-0d86-11eb-8438-7011b974d6f1.png)

wallsigns:
![image](https://user-images.githubusercontent.com/1935616/95892306-a336fa00-0d86-11eb-861a-7ea7008331ee.png)

conduits:
![image](https://user-images.githubusercontent.com/1935616/95894791-e34bac00-0d89-11eb-92a5-4648cd5fbb5d.png)

bannerposts and bannerwall:
![image](https://user-images.githubusercontent.com/1935616/95894839-f9f20300-0d89-11eb-9228-8d567963d9d8.png)

lanterns:
![image](https://user-images.githubusercontent.com/1935616/95894975-3887bd80-0d8a-11eb-9c81-a243be6d07c9.png)

wall (not single but the indented wall): 
![image](https://user-images.githubusercontent.com/1935616/95895270-b2b84200-0d8a-11eb-803e-ea3ce9dcb0b1.png)

Confirmed does not happen next to solid blocks: 
![image](https://user-images.githubusercontent.com/1935616/95891904-05432f80-0d86-11eb-9330-355591ff6390.png)

not with end rods either: 
![image](https://user-images.githubusercontent.com/1935616/95892013-26a41b80-0d86-11eb-83dc-487f78b7e041.png)

Also the following..
- tripwirehook
- single wallblockpost
- button
- redstonetorch
- anvil
- lever
- brewing stand
- heads (mob heads and player heads
- grindstone
- lectern
- bell
![image](https://user-images.githubusercontent.com/1935616/95895037-50f7d800-0d8a-11eb-8695-463bb6b0973c.png)

**Error / Logs**

**Additional context**

**Comment by Elikill58** [comment] 2020-10-13 19:52
There is something else. I failed to reproduce

**Comment by spetznack** [comment] 2020-10-14 14:04
What did you fail to reproduce? All of them? :S

**Comment by Elikill58** [comment] 2020-10-14 19:56
yes

**Comment by spetznack** [comment] 2020-10-14 20:35
Did you try to replicate using 1.9.5 or 1.9.6 beta?

**Comment by Elikill58** [comment] 2020-10-14 20:36
1.9.6-beta

**Comment by spetznack** [comment] 2020-10-26 19:49
I am pretty sure this was fixed for 1.9.6 beta when I was testing, but don't take my word for it. 
This is giving FP on v2 as well by the way.

**Comment by Elikill58** [comment] 2020-10-26 19:51
that's strange

**Comment by dkim19375** [comment] 2020-11-20 19:38
Shouldn't this issue be closed now? (Fixed with 1.9.6)

**Comment by Elikill58** [comment] 2020-11-20 19:41
No, because I don't know the state on v2, and spetz report it as false flag in v2 too.

**Comment by Elikill58** [comment] 2021-02-02 15:48
Failed to reproduce and any report for this error.
Re-open if appear again.

**Closed by Elikill58** 2021-02-02 15:48 UTC
Labels: failed to reproduce, false positive
