### ISSUE TITLE
Killaura dont working

### ISSUE THREAD

**Issue by Nevercold** [Elikill58/Negativity#124] opened 2020-05-02 14:46 UTC
Have Killaura and hit Player,
nothing happend.
screen: https://my-screen.eu/huZE1/ZEbeSiba08.mp4

**Comment by pinkpig3777** [comment] 2020-05-27 18:06
I'm a bit confused. Why is this marked as an enhancement? It is a bug.

Although may be hard to replicate as @Nevercold provided no details about his server type, sponge version, plugin version, etc.

**Comment by Elikill58** [comment] 2020-05-27 18:59
It's because it's not a bug, it's a bypass.
KillAura works, but it don't detect him at this point

**Comment by pinkpig3777** [comment] 2020-05-27 23:16
> 
> 
> It's because it's not a bug, it's a bypass.
> KillAura works, but it don't detect him at this point

Ah okay. Thanks for the quick reply!

**Comment by Elikill58** [comment] 2020-06-18 12:24
Fixed in https://github.com/Elikill58/Negativity/commit/3043ad6074ac789816e31b654f559a40cf549715

**Closed by Elikill58** 2020-06-18 12:24 UTC
Labels: enhancement
