### ISSUE TITLE
v2 NoFall false-positive when jumping in a 2.5 high space

### ISSUE THREAD

**Issue by spetznack** [Elikill58/Negativity#192] opened 2020-10-19 20:25 UTC
Describe the bug
NoFall false-positive when jumping in a 2.5 high space where you stand on top of a half-slab with air underneath. 
Happens consistently.

Your plugin version
Negativity_v2 16.10.2020

Your platform version (and precise the platforme (spigot/sponge))
PaperSpigot 1.16.3 build #212

Screenshots
![NoFall_false-positive_when_jumping_in_a_2 5_high_space_where_you_stand_on_top_of_a_half-slab_with_ai](https://user-images.githubusercontent.com/1935616/96507768-ecd98600-1259-11eb-888e-ce8e165f0396.gif)

Error / Logs
If applicable, add logs of error (copy/paste on pastebin/hastebin).

Additional context

**Comment by spetznack** [comment] 2020-10-22 16:57
Confirmed still gives this exact false positive in version Negativity_v2 20.10.2020

**Comment by Elikill58** [comment] 2020-10-22 17:33
So, reopen

**Comment by Elikill58** [comment] 2020-10-26 19:45
Duplicate of #200 , see fix on it

**Closed by Elikill58** 2020-10-26 19:45 UTC
Labels: false positive
