### ISSUE TITLE
[Bug] NoSuchMethodException MathHelper

### ISSUE THREAD

**Issue by e-motiv** [Elikill58/Negativity#384] opened 2023-05-24 15:26 UTC
### Which platform are you using ?

Java, Windows and server I think linux

### Versions of Negativity and of the server

Negativity v1.13, git-Paper-527 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: 6884092)

### Step to reproduce

Just starting the server

### Errors / Logs

24.05 15:21:39 [Server] WARN java.lang.NoSuchMethodException: net.minecraft.util.MathHelper.a([J)
24.05 15:21:39 [Server] WARN at java.base/java.lang.Class.getDeclaredMethod(Class.java:2675)
24.05 15:21:39 [Server] WARN at Negativity-1.13.jar//com.elikill58.negativity.spigot.SpigotNegativity.onEnable(SpigotNegativity.java:322)
24.05 15:21:39 [Server] WARN at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:279)
24.05 15:21:39 [Server] WARN at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189)
24.05 15:21:39 [Server] WARN at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
24.05 15:21:39 [Server] WARN at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
24.05 15:21:39 [Server] WARN at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugin(CraftServer.java:555)
24.05 15:21:39 [Server] WARN at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugins(CraftServer.java:466)
24.05 15:21:39 [Server] WARN at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:638)
24.05 15:21:39 [Server] WARN at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437)
24.05 15:21:39 [Server] WARN at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:308)
24.05 15:21:39 [Server] WARN at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1104)
24.05 15:21:39 [Server] WARN at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
24.05 15:21:39 [Server] WARN at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by Elikill58** [comment] 2023-05-24 15:31
Duplicate of #382 
Download working version here: [Negativity.zip](https://github.com/Elikill58/Negativity/files/11449878/Negativity.zip)

**Closed by Elikill58** 2023-05-24 15:31 UTC
Labels: bug
