### ISSUE TITLE
Could not pass event EntityDamageByEntityEvent to Negativity v1.5.2

### ISSUE THREAD

**Issue by eereeska** [Elikill58/Negativity#94] opened 2020-03-30 16:39 UTC
**Your plugin version**
1.5.2

**Your platform version (and precise the platforme (spigot/sponge))**
paper, 1.14.4

**Error / Logs**
RROR Could not pass event EntityDamageByEntityEvent to Negativity v1.5.2
30.03 19:36:56 [Server] INFO java.lang.NullPointerException: null
30.03 19:36:56 [Server] INFO at com.elikill58.negativity.spigot.protocols.ForceFieldProtocol.hasThorns(ForceFieldProtocol.java:84) ~[?:?]
30.03 19:36:56 [Server] INFO at com.elikill58.negativity.spigot.protocols.ForceFieldProtocol.onEntityDamageByEntity(ForceFieldProtocol.java:46) ~[?:?]
30.03 19:36:56 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor269.execute(Unknown Source) ~[?:?]
30.03 19:36:56 [Server] INFO at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.4.jar:git-Paper-243]
30.03 19:36:56 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.4.jar:git-Paper-243]
30.03 19:36:56 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.4.jar:git-Paper-243]
30.03 19:36:56 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.14.4.jar:git-Paper-243]
30.03 19:36:56 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:231) ~[patched_1.14.4.jar:git-Paper-243]
30.03 19:36:56 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:990) ~[patched_1.14.4.jar:git-Paper-243]
30.03 19:36:56 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:877) ~[patched_1.14.4.jar:git-Paper-243]
30.03 19:36:56 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:833) ~[patched_1.14.4.jar:git-Paper-243]
30.03 19:36:56 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1022) ~[patched_1.14.4.jar:git-Paper-243]
30.03 19:36:56 [Server] INFO at net.minecraft.server.v1_14_R1.EntityLiving.damageEntity0(EntityLiving.java:1686) ~[patched_1.14.4.jar:git-Paper-243]
30.03 19:36:56 [Server] INFO at net.minecraft.server.v1_14_R1.EntityLiving.damageEntity(EntityLiving.java:1095) ~[patched_1.14.4.jar:git-Paper-243]
30.03 19:36:56 [Server] INFO at net.minecraft.server.v1_14_R1.EntityMonster.damageEntity(EntityMonster.java:56) ~[patched_1.14.4.jar:git-Paper-243]
30.03 19:36:56 [Server] INFO at net.minecraft.server.v1_14_R1.EntityZombie.damageEntity(EntityZombie.java:284) ~[patched_1.14.4.jar:git-Paper-243]
30.03 19:36:56 [Server] INFO at net.minecraft.server.v1_14_R1.EntityHuman.attack(EntityHuman.java:1047) ~[patched_1.14.4.jar:git-Paper-243]
30.03 19:36:56 [Server] INFO at net.minecraft.server.v1_14_R1.EntityPlayer.attack(EntityPlayer.java:1691) ~[patched_1.14.4.jar:git-Paper-243]
30.03 19:36:56 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:2035) ~[patched_1.14.4.jar:git-Paper-243]
30.03 19:36:56 [Server] INFO at net.minecraft.server.v1_14_R1.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:51) ~[patched_1.14.4.jar:git-Paper-243]
30.03 19:36:56 [Server] INFO at net.minecraft.server.v1_14_R1.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:6) ~[patched_1.14.4.jar:git-Paper-243]
30.03 19:36:56 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.14.4.jar:git-Paper-243]
30.03 19:36:56 [Server] INFO at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.4.jar:git-Paper-243]
30.03 19:36:56 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.14.4.jar:git-Paper-243]
30.03 19:36:56 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.4.jar:git-Paper-243]
30.03 19:36:56 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.14.4.jar:git-Paper-243]
30.03 19:36:56 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1029) ~[patched_1.14.4.jar:git-Paper-243]
30.03 19:36:56 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:1022) ~[patched_1.14.4.jar:git-Paper-243]
30.03 19:36:56 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.14.4.jar:git-Paper-243]
30.03 19:36:56 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1006) ~[patched_1.14.4.jar:git-Paper-243]
30.03 19:36:56 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:929) ~[patched_1.14.4.jar:git-Paper-243]
30.03 19:36:56 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_112]

**Comment by RedNesto** [comment] 2020-03-30 17:00
Duplicate of #90

**Closed by RedNesto** 2020-03-30 17:00 UTC
Labels: bug
